package com.CorbaHibernate.CountryCapital;


/**
* CountryCapital/CountryCapitalTestPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CountryCapital.idl
* Tuesday, January 23, 2024 2:40:06 PM CET
*/

public abstract class CountryCapitalTestPOA extends org.omg.PortableServer.Servant
 implements com.CorbaHibernate.CountryCapital.CountryCapitalTestOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("putValues", new java.lang.Integer (0));
    _methods.put ("getCapital", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CountryCapital/CountryCapitalTest/putValues
       {
         int id = in.read_long ();
         String country = in.read_string ();
         String capital = in.read_string ();
         String $result = null;
         $result = this.putValues (id, country, capital);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CountryCapital/CountryCapitalTest/getCapital
       {
         String country = in.read_string ();
         String $result = null;
         $result = this.getCapital (country);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CountryCapital/CountryCapitalTest:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CountryCapitalTest _this() 
  {
    return CountryCapitalTestHelper.narrow(
    super._this_object());
  }

  public CountryCapitalTest _this(org.omg.CORBA.ORB orb) 
  {
    return CountryCapitalTestHelper.narrow(
    super._this_object(orb));
  }


} // class CountryCapitalTestPOA
