package com.CorbaHibernate.CountryCapital;


/**
* CountryCapital/CountryCapitalTestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CountryCapital.idl
* Tuesday, January 23, 2024 2:40:06 PM CET
*/

public interface CountryCapitalTestOperations 
{
  String putValues (int id, String country, String capital);
  String getCapital (String country);
} // interface CountryCapitalTestOperations
