package com.CorbaHibernate.CountryCapital;


/**
* CountryCapital/CountryCapitalTest.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CountryCapital.idl
* Tuesday, January 23, 2024 2:40:06 PM CET
*/

public interface CountryCapitalTest extends CountryCapitalTestOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CountryCapitalTest
