package com.CorbaHibernate.CountryCapital;

/**
* CountryCapital/CountryCapitalTestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CountryCapital.idl
* Tuesday, January 23, 2024 2:40:06 PM CET
*/

public final class CountryCapitalTestHolder implements org.omg.CORBA.portable.Streamable
{
  public com.CorbaHibernate.CountryCapital.CountryCapitalTest value = null;

  public CountryCapitalTestHolder ()
  {
  }

  public CountryCapitalTestHolder (com.CorbaHibernate.CountryCapital.CountryCapitalTest initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.CorbaHibernate.CountryCapital.CountryCapitalTestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.CorbaHibernate.CountryCapital.CountryCapitalTestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.CorbaHibernate.CountryCapital.CountryCapitalTestHelper.type ();
  }

}
