package com.CorbaHibernate.CountryCapital;

/**
* CountryCapital/DataSetHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CountryCapital.idl
* Tuesday, January 23, 2024 2:40:06 PM CET
*/

public final class DataSetHolder implements org.omg.CORBA.portable.Streamable
{
  public com.CorbaHibernate.CountryCapital.DataSet value = null;

  public DataSetHolder ()
  {
  }

  public DataSetHolder (com.CorbaHibernate.CountryCapital.DataSet initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.CorbaHibernate.CountryCapital.DataSetHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.CorbaHibernate.CountryCapital.DataSetHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.CorbaHibernate.CountryCapital.DataSetHelper.type ();
  }

}
