package GraphCore;


/**
* GraphCore/GraphCoreTest.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/GraphCore.idl
* Friday, August 20, 2021 1:09:22 AM CEST
*/

public interface GraphCoreTest extends GraphCoreTestOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GraphCoreTest
