package GraphCore;


/**
* GraphCore/GraphCoreTestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/GraphCore.idl
* Friday, August 20, 2021 1:09:22 AM CEST
*/

public interface GraphCoreTestOperations 
{
  String putValues (String country, String capital);
  String getCapital (String country);
} // interface GraphCoreTestOperations
