package GraphCore;


/**
* GraphCore/GraphCoreTestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/GraphCore.idl
* Tuesday, August 31, 2021 9:44:40 PM CEST
*/

public interface GraphCoreTestOperations 
{
  String putValues (int id, String country, String capital);
  String getCapital (String country);
} // interface GraphCoreTestOperations
