package GraphCore;

/**
* GraphCore/GraphCoreTestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/GraphCore.idl
* Friday, August 20, 2021 9:59:39 PM CEST
*/

public final class GraphCoreTestHolder implements org.omg.CORBA.portable.Streamable
{
  public GraphCore.GraphCoreTest value = null;

  public GraphCoreTestHolder ()
  {
  }

  public GraphCoreTestHolder (GraphCore.GraphCoreTest initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GraphCore.GraphCoreTestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GraphCore.GraphCoreTestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GraphCore.GraphCoreTestHelper.type ();
  }

}
