package GraphCore;


/**
* GraphCore/GraphCoreTest.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/GraphCore.idl
* Tuesday, August 31, 2021 9:44:40 PM CEST
*/

public interface GraphCoreTest extends GraphCoreTestOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GraphCoreTest
